version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=210953236598.dkr.ecr.us-east-1.amazonaws.com/ecs-cicd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t image:latest .
      - docker tag image:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo we are in post_build now.
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"ecscicd","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json
      - cat imagedefinition.json   
artifacts:
  files:
    - imagedefination.json
    - '**/*'

